# Generated by Django 4.2.11 on 2024-05-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbotapp', '0002_category_month_category_price_category_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='month',
        ),
        migrations.RemoveField(
            model_name='category',
            name='price',
        ),
        migrations.RemoveField(
            model_name='category',
            name='year',
        ),
        migrations.AddField(
            model_name='category',
            name='exp',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
